version: '3.8'

services:
  # --- DATABASES ---
  db_postgres:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: klhdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_mongo:
    image: mongo:6.0
    container_name: db_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db_redis:
    image: redis:7-alpine
    container_name: db_redis
    restart: always
    ports:
      - "6379:6379"

  # --- MAIN APPLICATION ---
  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexcommerce_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db_postgres
      - db_mongo
      - db_redis
    environment:
      - DATABASE_URL=postgresql://postgres:Admin%40123@db_postgres:5432/klhdb
      - PG_HOST=db_postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=Admin@123
      - PG_DATABASE=klhdb
      - MONGO_URI=mongodb://db_mongo:27017
      - MONGO_DB_NAME=distributed_commerce_db
      - REDIS_URI=redis://db_redis:6379/0
      - REDIS_HOST=db_redis
      - REDIS_PORT=6379
      - JWT_SECRET=kl_university_dbs_dbd_secret_key_2026
      - RAZORPAY_KEY_ID=rzp_test_placeholder
      - RAZORPAY_KEY_SECRET=placeholder_secret
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data:
