server.port=8080
spring.application.name=springboot-inventory-service

# PostgreSQL Database Configuration (klhdb)
spring.datasource.url=jdbc:postgresql://localhost:5432/klhdb
spring.datasource.username=postgres
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Health Metrics
management.endpoints.web.exposure.include=health,info,metrics
